# Generated by Django 2.0.7 on 2018-07-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObsField',
            fields=[
                ('field_no', models.IntegerField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=90, unique=True)),
                ('ra', models.DecimalField(decimal_places=5, max_digits=8)),
                ('dec', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                'db_table': 'obs_field',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObsRecords',
            fields=[
                ('idobs_records', models.AutoField(primary_key=True, serialize=False)),
                ('star_id', models.CharField(max_length=45)),
                ('star_name', models.CharField(blank=True, max_length=45, null=True)),
                ('sp_type', models.CharField(blank=True, max_length=45, null=True)),
                ('obs_start', models.CharField(max_length=45)),
                ('obs_end', models.CharField(max_length=45)),
                ('no_obs', models.IntegerField()),
                ('obs_mode', models.CharField(max_length=10)),
                ('availability', models.CharField(max_length=45)),
                ('field_no', models.ForeignKey(db_column='field_no', on_delete=django.db.models.deletion.DO_NOTHING, to='wiki.ObsField')),
            ],
            options={
                'db_table': 'obs_records',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('sat_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'satellite',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('field_status', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Status',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='obsrecords',
            name='sat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wiki.Satellite'),
        ),
        migrations.AddField(
            model_name='obsfield',
            name='field_status',
            field=models.ForeignKey(db_column='field_status', on_delete=django.db.models.deletion.DO_NOTHING, to='wiki.Status'),
        ),
    ]
